import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/ui/navbar";
import { geistSans, geistMono } from "@/lib/fonts";
import { FavouritesProvider } from "@/context/favcontext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavBar />
        <FavouritesProvider>
          {children}
        </FavouritesProvider>
      </body>
    </html>
  );
}
